name: Zip Each Directory Separately

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip-directories:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP files for each directory (excluding .git)
        run: |
          shopt -s dotglob  # Include hidden files
          for dir in */; do
            if [ -d "$dir" ]; then  # Ensure it's a directory
              zip -r "${dir%/}.zip" "$dir" -x "$dir.git/*"  # Exclude .git directory
            fi
          done

      - name: Upload each ZIP as a separate artifact
        uses: actions/upload-artifact@v4
        with:
          path: "*.zip"
          if-no-files-found: error  # Fail the job if no ZIPs are found
