name: Zip Each Directory Separately

on: 
  push:
    branches:
      - main  # Adjust if needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  zip-directories:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP files for each directory (excluding files)
        run: |
          shopt -s dotglob  # Include hidden files
          for dir in */; do
            if [ -d "$dir" ]; then  # Ensure it's a directory
              zip -r "${dir%/}.zip" "$dir"
            fi
          done

      - name: Upload Each ZIP as a Separate Artifact
        run: |
          for zipfile in *.zip; do
            gh run upload-artifact --name "${zipfile%.zip}" --path "$zipfile"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
