name: Zip Each Directory Separately

on: 
  push:
    branches:
      - main  # or master, adjust as needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  zip-directories:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP files for each directory
        run: |
          shopt -s dotglob  # Include hidden files
          for dir in */; do
            if [ -d "$dir" ]; then  # Ensure it's a directory
              zip -r "${dir%/}.zip" "$dir"
            fi
          done

      - name: Upload ZIP files as separate artifacts
        run: |
          for zipfile in *.zip; do
            echo "Uploading $zipfile"
            # Upload each zip file as a separate artifact
            gh release upload ${{ github.ref }} "$zipfile" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

