name: Zip Each Directory Separately

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip-directories:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP files for each directory
        run: |
          shopt -s dotglob  # Include hidden files
          for dir in */; do
            if [ -d "$dir" ]; then  # Ensure it's a directory
              zip -r "${dir%/}.zip" "$dir"
            fi
          done

      - name: Upload Each ZIP Separately
        uses: actions/upload-artifact@v4
        with:
          name: zipped-${{ matrix.dir }}
          path: ${{ matrix.dir }}.zip

    strategy:
      matrix:
        dir: 
          - $(ls -d */ | sed 's#/##')  # List directories dynamically
