name: Zip Each Directories

on: 
  push:
    branches:
      - main  # Adjust if needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  zip-directories:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP files for each directory (excluding files)
        run: |
          shopt -s dotglob  # Include hidden files
          for dir in */; do
            if [ -d "$dir" ]; then  # Ensure it's a directory
              zip -r "${dir%/}.zip" "$dir"
            fi
          done

      - name: Upload ZIPs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zipped-directories
          path: "*.zip"
