name: Zip Each Directory Separately

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip:
    name: Create ZIP Files
    runs-on: ubuntu-latest
    outputs:
      zip_files: ${{ steps.collect.outputs.zip_files }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP files for each directory (excluding .git)
        run: |
          # Enable globbing of dotfiles if needed
          shopt -s dotglob
          for dir in */; do
            if [ -d "$dir" ]; then
              echo "Zipping $dir..."
              zip -r "${dir%/}.zip" "$dir" -x "$dir/.git/*"
            fi
          done

      - name: Upload created ZIP files for later retrieval
        uses: actions/upload-artifact@v4
        with:
          name: zips
          path: "*.zip"

      - name: List and collect ZIP filenames
        id: collect
        run: |
          echo "Found ZIP files:"
          ls -1 *.zip
          # Create a JSON array of zip filenames (e.g., ["dir1.zip","dir2.zip",...])
          zip_files=$(ls -1 *.zip | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "ZIP files JSON: $zip_files"
          # Set the output using the new recommended method:
          echo "zip_files=$zip_files" >> $GITHUB_OUTPUT

  upload:
    name: Upload Each ZIP as Its Own Artifact
    runs-on: ubuntu-latest
    needs: zip
    strategy:
      matrix:
        zip_file: ${{ fromJson(needs.zip.outputs.zip_files) }}
    steps:
      - name: Download all ZIP files artifact
        uses: actions/download-artifact@v4
        with:
          name: zips
          path: .

      - name: Upload individual artifact for ${{ matrix.zip_file }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.zip_file }}
          path: ${{ matrix.zip_file }}
